# Form implementation generated from reading ui file 'Task1.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(669, 514)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 57)")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.right_video = QtWidgets.QLabel(parent=self.centralwidget)
        self.right_video.setGeometry(QtCore.QRect(380, 260, 251, 161))
        self.right_video.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.right_video.setText("")
        self.right_video.setObjectName("right_video")
        self.left_video = QtWidgets.QLabel(parent=self.centralwidget)
        self.left_video.setGeometry(QtCore.QRect(20, 260, 251, 161))
        self.left_video.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.left_video.setText("")
        self.left_video.setObjectName("left_video")
        self.stitched_video = QtWidgets.QLabel(parent=self.centralwidget)
        self.stitched_video.setGeometry(QtCore.QRect(90, 10, 471, 201))
        self.stitched_video.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.stitched_video.setText("")
        self.stitched_video.setObjectName("stitched_video")
        self.Right_Camera = QtWidgets.QLabel(parent=self.centralwidget)
        self.Right_Camera.setGeometry(QtCore.QRect(460, 430, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Right_Camera.setFont(font)
        self.Right_Camera.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.Right_Camera.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Right_Camera.setObjectName("Right_Camera")
        self.Right_Camera_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.Right_Camera_2.setGeometry(QtCore.QRect(90, 430, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Right_Camera_2.setFont(font)
        self.Right_Camera_2.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.Right_Camera_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Right_Camera_2.setObjectName("Left_camera_text")
        self.Right_Camera_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.Right_Camera_3.setGeometry(QtCore.QRect(220, 220, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Right_Camera_3.setFont(font)
        self.Right_Camera_3.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.Right_Camera_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Right_Camera_3.setObjectName("Stitched_video_text")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Right_Camera.setText(_translate("MainWindow", "Right Camera"))
        self.Right_Camera_2.setText(_translate("MainWindow", "Left Camera"))
        self.Right_Camera_3.setText(_translate("MainWindow", "Stitched Video"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
